// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3BPuW24ykRiCZGZ6aYu_O_7SNjqnWyLQ',
    appId: '1:337995725399:web:05155f44e3ca7b33d20112',
    messagingSenderId: '337995725399',
    projectId: 'insta-f8e11',
    authDomain: 'insta-f8e11.firebaseapp.com',
    storageBucket: 'insta-f8e11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCCwVwWEWsm-JfLgJElWeMdxA5aK-iik4',
    appId: '1:337995725399:android:2bc59f8f28ccc609d20112',
    messagingSenderId: '337995725399',
    projectId: 'insta-f8e11',
    storageBucket: 'insta-f8e11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyvMqHkXgz7bjnO_8pdImpDOlr_ND2t_k',
    appId: '1:337995725399:ios:aaef93d2be0c03c3d20112',
    messagingSenderId: '337995725399',
    projectId: 'insta-f8e11',
    storageBucket: 'insta-f8e11.appspot.com',
    iosClientId: '337995725399-5aj27mgnqck2chb5fqftfi94c53kad08.apps.googleusercontent.com',
    iosBundleId: 'com.pocketcrafts.insta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyvMqHkXgz7bjnO_8pdImpDOlr_ND2t_k',
    appId: '1:337995725399:ios:68f281482f3840ced20112',
    messagingSenderId: '337995725399',
    projectId: 'insta-f8e11',
    storageBucket: 'insta-f8e11.appspot.com',
    iosClientId: '337995725399-ov6lrrosfa4icic4mejmoemsbmegbos0.apps.googleusercontent.com',
    iosBundleId: 'com.pocketcrafts.insta.RunnerTests',
  );
}
